=== enigmasys/MetaDataParser/FullAIIntegration/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Device": {
      "type": "object",
      "properties": {
        "Device Type": {
          "type": "string"
        },
        "Device Model": {
          "type": "string"
        },
        "Device Unique Serial Code": {
          "type": "string"
        },
        "Device Firmware Version": {
          "type": "string"
        },
        "Calibration Date": {
          "type": "string"
        },
        "Application name & version": {
          "type": "string"
        }
      },
      "required": [
        "Device Type",
        "Device Model",
        "Device Unique Serial Code",
        "Device Firmware Version",
        "Calibration Date",
        "Application name & version"
      ]
    },
    "Measurement": {
      "type": "object",
      "properties": {
        "Measurement Frequency": {
          "type": "string"
        },
        "Start Time": {
          "type": "string"
        },
        "Last measurement": {
          "type": "string"
        },
        "Device Location Code": {
          "type": "string"
        },
        "Time Zone": {
          "type": "string"
        }
      },
      "required": [
        "Measurement Frequency",
        "Start Time",
        "Last measurement",
        "Device Location Code",
        "Time Zone"
      ]
    },
    "Subject": {
      "type": "object",
      "properties": {
        "Subject Code": {
          "type": "string"
        },
        "Date of Birth": {
          "type": "string"
        },
        "Sex": {
          "type": "string"
        },
        "Height": {
          "type": "string"
        },
        "Weight": {
          "type": "string"
        },
        "Handedness Code": {
          "type": "string"
        },
        "Subject Notes": {
          "type": "string"
        }
      },
      "required": [
        "Subject Code",
        "Date of Birth",
        "Sex",
        "Height",
        "Weight",
        "Handedness Code",
        "Subject Notes"
      ]
    },
    "Study Center": {
      "type": "object",
      "properties": {
        "Study Centre": {
          "type": "string"
        },
        "Study Code": {
          "type": "string"
        },
        "Investigator ID": {
          "type": "string"
        },
        "Exercise Type": {
          "type": "string"
        },
        "Config Operator ID": {
          "type": "string"
        },
        "Config Time": {
          "type": "string"
        },
        "Config Notes": {
          "type": "string"
        },
        "Extract Operator ID": {
          "type": "string"
        },
        "Extract Time": {
          "type": "string"
        },
        "Extract Notes": {
          "type": "string"
        }
      },
      "required": [
        "Study Centre",
        "Study Code",
        "Investigator ID",
        "Exercise Type",
        "Config Operator ID",
        "Config Time",
        "Config Notes",
        "Extract Operator ID",
        "Extract Time",
        "Extract Notes"
      ]
    },
    "Sensor": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "Sensor type": {
              "type": "string"
            },
            "Range": {
              "type": "string"
            },
            "Resolution": {
              "type": "string"
            },
            "Units": {
              "type": "string"
            },
            "Additional information": {
              "type": "string"
            }
          },
          "required": [
            "Sensor type",
            "Range",
            "Resolution",
            "Units",
            "Additional information"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Sensor type": {
              "type": "string"
            },
            "Range": {
              "type": "string"
            },
            "Resolution": {
              "type": "string"
            },
            "Units": {
              "type": "string"
            },
            "Additional information": {
              "type": "string"
            }
          },
          "required": [
            "Sensor type",
            "Range",
            "Resolution",
            "Units",
            "Additional information"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Sensor type": {
              "type": "string"
            },
            "Range": {
              "type": "string"
            },
            "Resolution": {
              "type": "string"
            },
            "Units": {
              "type": "string"
            },
            "Additional information": {
              "type": "string"
            }
          },
          "required": [
            "Sensor type",
            "Range",
            "Resolution",
            "Units",
            "Additional information"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Sensor type": {
              "type": "string"
            },
            "Range": {
              "type": "string"
            },
            "Resolution": {
              "type": "string"
            },
            "Units": {
              "type": "string"
            },
            "Additional information": {
              "type": "string"
            }
          },
          "required": [
            "Sensor type",
            "Range",
            "Resolution",
            "Units",
            "Additional information"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Sensor type": {
              "type": "string"
            },
            "Range": {
              "type": "string"
            },
            "Resolution": {
              "type": "string"
            },
            "Units": {
              "type": "string"
            },
            "Additional information": {
              "type": "string"
            }
          },
          "required": [
            "Sensor type",
            "Range",
            "Resolution",
            "Units",
            "Additional information"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Sensor type": {
              "type": "string"
            },
            "Range": {
              "type": "string"
            },
            "Resolution": {
              "type": "string"
            },
            "Units": {
              "type": "string"
            },
            "Additional information": {
              "type": "string"
            }
          },
          "required": [
            "Sensor type",
            "Range",
            "Resolution",
            "Units",
            "Additional information"
          ]
        }
      ]
    }
  },
  "required": [
    "Device",
    "Measurement",
    "Subject",
    "Study Center",
    "Sensor"
  ]
}

=== enigmasys/MetaDataParser/FullAIIntegration/my_output.json
{
    "Device": {
        "Device Type": "GENEActiv",
        "Device Model": "1.1",
        "Device Unique Serial Code": "11152",
        "Device Firmware Version": "Ver1.30 date 05Aug11",
        "Calibration Date": "2011-09-07 19:20:18:000",
        "Application name & version": "GENEActiv PC Software 2.1"
    },
    "Measurement": {
        "Measurement Frequency": "100 Hz",
        "Start Time": "2011-10-09 10:20:00:000",
        "Last measurement": "",
        "Device Location Code": "right wrist",
        "Time Zone": "GMT +01"
    },
    "Subject": {
        "Subject Code": "Example",
        "Date of Birth": "01/01/1900",
        "Sex": "",
        "Height": "178",
        "Weight": "67",
        "Handedness Code": "right",
        "Subject Notes": ""
    },
    "Study Center": {
        "Study Centre": "",
        "Study Code": "",
        "Investigator ID": "",
        "Exercise Type": "",
        "Config Operator ID": "",
        "Config Time": "2011-10-09 10:16:39:671:",
        "Config Notes": "Notes",
        "Extract Operator ID": "",
        "Extract Time": "2011-10-9 11:24:8:453",
        "Extract Notes": ""
    },
    "Sensor": [
        {
            "Sensor type": "MEMS accelerometer x-axis",
            "Range": "-8 to 8",
            "Resolution": "0.0039",
            "Units": "g",
            "Additional information": ""
        },
        {
            "Sensor type": "MEMS accelerometer y-axis",
            "Range": "-8 to 8",
            "Resolution": "0.0039",
            "Units": "g",
            "Additional information": ""
        },
        {
            "Sensor type": "MEMS accelerometer z-axis",
            "Range": "-8 to 8",
            "Resolution": "0.0039",
            "Units": "g",
            "Additional information": ""
        },
        {
            "Sensor type": "Lux Photodiode 400nm - 1100nm",
            "Range": "0 to 5000",
            "Resolution": "5",
            "Units": "lux",
            "Additional information": ""
        },
        {
            "Sensor type": "User button event marker",
            "Range": "1 or 0",
            "Resolution": "",
            "Units": "",
            "Additional information": "1=pressed"
        },
        {
            "Sensor type": "Linear active thermistor",
            "Range": "0 to 70",
            "Resolution": "0.1",
            "Units": "deg. C",
            "Additional information": ""
        }
    ]
}
